"""Change Join

Revision ID: 05b2a37d16a8
Revises: e546e8eb08e3
Create Date: 2023-04-27 12:27:23.087952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b2a37d16a8'
down_revision = 'e546e8eb08e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('song_samples_join')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_samples_join',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('volume', sa.FLOAT(), nullable=True),
    sa.Column('song_id', sa.INTEGER(), nullable=True),
    sa.Column('sample_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('song_samples')
    # ### end Alembic commands ###
